# Generated by Django 5.2.17 on 2026-08-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_basic_access_permission(apps, schema_editor):
    """Django leaves the Permission and ContentType rows behind when a model goes
    away, so basic_access would keep showing up in the group and state admin."""
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission.objects.filter(
        content_type__app_label="outline", codename="basic_access"
    ).delete()
    ContentType.objects.filter(app_label="outline", model="general").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=5)),
                ('match', models.CharField(choices=[('exact', 'Exact name'), ('prefix', 'Name prefix'), ('regex', 'Regex'), ('internal', 'Internal group flag')], max_length=8)),
                ('value', models.CharField(blank=True, help_text='Ignored for the internal group flag match.', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'group sync rule',
                'default_permissions': (),
                'unique_together': {('action', 'match', 'value')},
            },
        ),
        migrations.CreateModel(
            name='OutlineUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='outline', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('outline_user_id', models.CharField(db_index=True, max_length=36)),
                ('email', models.CharField(max_length=254)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': (('access_outline', 'Can access the Outline service'),),
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.RunPython(
            drop_basic_access_permission, migrations.RunPython.noop
        ),
    ]
